version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-browsers
    steps:
      - checkout
      - run:
          name: Install depenedencies
          command: bundle install
      - run:
          name: Build staging docs
          command: |
            JEKYLL_ENV=staging bundle exec jekyll build --config jekyll/_config.yml,jekyll/_config_staging.yml --source jekyll --destination jekyll/_site/staging/docs
      - run:
          name: Build production docs
          command: |
            JEKYLL_ENV=production bundle exec jekyll build --config jekyll/_config.yml,jekyll/_config_production.yml --source jekyll --destination jekyll/_site/production/docs/
      - run:
          name: Deploy docs to production or staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bundle exec s3_website push --site jekyll/_site/production
            else
              bundle exec s3_website push --config-dir staging --site jekyll/_site/staging
            fi
