version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-browsers
    steps:
      - checkout
      - run:
          name: Install depenedencies
          command: bundle install
      - run:
          name: Build staging docs
          command: |
            JEKYLL_ENV=staging bundle exec jekyll build --config jekyll/_config.yml,jekyll/_config_staging.yml --source jekyll --destination jekyll/_site/staging/docs
      - run:
          name: Build production docs
          command: |
            JEKYLL_ENV=production bundle exec jekyll build --config jekyll/_config.yml,jekyll/_config_production.yml --source jekyll --destination jekyll/_site/production/docs/
      - run:
          name: Deploy docs to production or staging
          command: |
            # We tell the s3_website gem to only download the .jar file, and
            # then we manually invoke it. This was added as a workaround for
            # error `Failed to parse ERB in staging/s3_website.yml`.
            # There will probably be a different long-term fix when
            # https://github.com/laurilehmijoki/s3_website/issues/323 is
            # resolved.
            bundle exec s3_website install
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              java -cp $(bundle show s3_website)/*.jar s3.website.Push --site jekyll/_site/production
            else
              java -cp $(bundle show s3_website)/*.jar s3.website.Push --config-dir staging --site jekyll/_site/staging
            fi
